autocertkit/utils.py

Now, ACK checks allowed operations to VM instead of power state. This is kind of work-around of XAPI pitfall that happens after async call back failure. (raised related defect ticket)

Change way of removing VM.

---

autocertkit/utils.py

'allowed_operations' is not garunteed to be updated in time. Hence
changed it again to use 'power_state' and 'current_operations'.

Changed way of checking status of VM when it is cleaned up.

---

autocertkit/utils.py

All xapi issues are fixed now.
Work-arounds are not required any more.

Revert XAPI issue work-arounds

---

autocertkit/utils.py

The bug is fixed but requires hotfixes in 6.x. To avoid partner's inconvenience, reapplying the work-around.

Re-applying workaround for CA-146164

---

mk/acktools-setup.py
setup.py

Includes XenServer 6.5 SP1 support and bug fixes.

Release new ACK v0.9.1.

---

autocertkit/network_tests.py
autocertkit/testbase.py
autocertkit/utils.py
plugins/autocertkit

1. Now IP is flushed instead setting 0.0.0.0.
2. IP parser from ifconfig is now working for all supported XSes.
3. iptables is not called with service.d instead of legacy init.d style.
4. minor cosmetics updated.
5. Many minor bug fixes and improvements.

Fixed issues with updated Dom0 in the next release of XS

---

autocertkit/operations_tests.py

tested on trunk. code working. previous changes were tested on clearwater as well and skipping check on it this time as no changes which might cause issue on python 2.4

Fixed issue with crashdump test, test checks for crashdump created during host crash. #105

---

acktools/net/tests/route_tests.py

Made route_tests.py to use mock.patch instead of hard-coded replacement.
Also removed local method call test as it causes Travis error, which adds small value considering it only covers 1 line and it passes in local environment.

Changed hard-coded mocking functions into mock.patch

---

autocertkit/tests/utils_tests.py
autocertkit/tests/xenapi_mock.py

This also includes pool mock in xenapi_mock module.

Added more unit tests for utils module

---

autocertkit/tests/utils_tests.py
autocertkit/tests/xenapi_mock.py

1. Make Session more elegant way with new class style.
2. Make Pool is more sensible way to match with real xenapi Session. Session suppose to have only 1 pool always.
3. Removed unnecessary tailing white spaces.
4. Minor bug fixes in VM mock class.

Improved XenAPI mock

---

plugins/autocertkit

Getting device bridge on none-tested nic, should not stop running test.

Removed unnecessary block from util func.

---

autocertkit/network_tests.py

Removed wrong exception

---

autocertkit/test_runner.py

Also removing extra lines nearby.

removing unused import call, spamming warning in ack log

---

autocertkit/ack_cli.py
autocertkit/cpu_tests.py
autocertkit/network_tests.py
autocertkit/storage_tests.py
autocertkit/testbase.py
autocertkit/tests/xenapi_mock.py
autocertkit/utils.py
plugins/autocertkit

Issue: https://issues.citrite.net/browse/CP-18237
Tested ACK manually for all tests using:
```
cd /opt/xensource/packages/files/auto-cert-kit/
python ack_cli.py -n networkconf
```
____
No new unittests identifies for this change, though new unittests are required in ACK to cover max scenarios and will be added as separate work.

Changing ack plugin output format from xml to json

---

mk/acktools-setup.py
setup.py

Changelog (Previous v1.0.1):
- improvement: ACK plugin output is JSON instead of XML
- fix: pylint call updated
- improvement: added autopep8
- includes minor code fixes and improvements

Updated to version 1.1.0

---

autocertkit/models.py
autocertkit/network_tests.py
autocertkit/utils.py

Signed-off-by: Liang Dai <liang.dai1@citrix.com>

CP-21475: Add multicast test for auto-cert-kit

---

acktools/__init__.py
autocertkit/ack_cli.py
autocertkit/networkconf.example
autocertkit/tests/frontend-test.py

Signed-off-by: Deli Zhang <Deli.Zhang@citrix.com>

CP-27478: Change network config file format to ini

---

autocertkit/cpu_tests.py
autocertkit/models.py
autocertkit/ssh.py
autocertkit/tests/model_tests.py
autocertkit/utils.py
plugins/autocertkit

Signed-off-by: Deli Zhang <Deli.Zhang@citrix.com>

CP-27559: Refactor SSHCommand

---

plugins/autocertkit

Signed-off-by: Deli Zhang <Deli.Zhang@citrix.com>

CA-309411: Fix issue of getting incorrect bridge by device

---

plugins/autocertkit

Signed-off-by: Deli Zhang <Deli.Zhang@citrix.com>

CA-312462: Avoid using iperf daemon mode

---

auto-cert-kit.service

Signed-off-by: Deli Zhang <deli.zhang@citrix.com>

CA-334921: Fix start-pre timeout issue

---

autocertkit/network_tests.py
plugins/autocertkit

Signed-off-by: alexhimmel <alex.ac@qq.com>

CP-35758: write sysctl configuration to file

---

LICENCE
acktools/log.py
acktools/net/route.py
acktools/utils.py
autocertkit/ack_cli.py
autocertkit/cpu_tests.py
autocertkit/models.py
autocertkit/network_tests.py
autocertkit/operations_tests.py
autocertkit/ssh.py
autocertkit/status.py
autocertkit/storage_tests.py
autocertkit/test_generators.py
autocertkit/test_report.py
autocertkit/test_runner.py
autocertkit/testbase.py
autocertkit/utils.py
plugins/autocertkit
setup.py

Signed-off-by: alexhimmel <alex.ac@qq.com>

CP-40974: change company name and product name

---

vm_setup_scripts/init-run.sh
vm_setup_scripts/startup-ip.service
vm_setup_scripts/static-ip.sh

Signed-off-by: alexhimmel <alex.ac@qq.com>

CP-41461: add vm_setup_scripts in ACK repo

---

autocertkit/network_tests.py
autocertkit/utils.py
plugins/autocertkit
setup-scripts/init-run.sh

To avoid accidently failure of iperf test

CA-374877: Double check the iperf test result against the tcpdump result

---

autocertkit/ack_cli.py
autocertkit/models.py
autocertkit/status.py
autocertkit/test_runner.py

Tested 5 times and passed:
Job id: 3877217-3877221

CA-374374: Add mechanism to automatically re-run the failed test cases
