autocertkit/network_tests.py
autocertkit/utils.py
plugins/autocertkit

When ACK turns 'up' or 'down' a pif with 'ifconfig',
ACK now checks operstate, carrier state and physical link from ifconfig and
ethtool outputs.
This may help some environment and device driver that takes a few seconds to change link state.

Wait link state is fully changed when changing nic state

---

autocertkit/utils.py

XAPI synchronize its DB every 5 mins. To prevent any XAPI data loss, it is safer to force synchronize before crash test.

Force synchronize XAPI DB before crash test.

---

autocertkit/utils.py

When Droid VM has multiple NICS with static IP manager, in some environment,
eth1 of VM may have IP a bit later than eth0. This sometimes causes iperf packet
sending failure.

Fix for late ip binding in 2nd VIF issue.

---

README.md

as per title, travis-ci badge was still pointing at rdobson account

fix travis-ci badge to point to the xenserver owned repo

---

Makefile

This changes to use customised create demo VM, not a demo VM from XS builds.
For now, demo VM from old XS is being used.

Changed to use Demo VM from distfiles.

---

autocertkit/utils.py
plugins/autocertkit

Device name can differ from network bridge, which XS only concerns as interface level.
Now XS does not mock dummy interface to match local device/bridge. Hence ACK needs a logic to find bridge from device name.

Fixed false failure on Bonding tests

---

autocertkit/tests/utils_tests.py
autocertkit/tests/xenapi_mock.py
autocertkit/utils.py

Host needs to be ckecked not only enabled but also it is live in network.
By checking 'liveness' additionally, we can make sure all hosts are connected and available for API calls.

Enhanced host enability checks.

---

autocertkit/tests/utils_tests.py
autocertkit/tests/xenapi_mock.py
autocertkit/utils.py

Even though host is 'enabled' and 'live' xapi may not respond in time due to host enability changing timing. To work-around this added ip checking, to make sure it is fully up and reachable via management network, and enhanced route checking routine to retry a few times in case it is not in responsive in time.

Enhanced host up checking routine

---

autocertkit/utils.py

This happens due to a bug in wait_for_hosts.

Fixed ACK crash on restarting host

---

autocertkit/utils.py

New host check routine used XS 6.1+ feature. Changed it to support XS 6.0.

Improved backward compatibility

---

Makefile
autocertkit/ack_cli.py
autocertkit/testbase.py
autocertkit/utils.py
setup-supp-pack.py

1. Now ACK supports from XenServer 6.0 and onwards
2. Now ACK requires platform (XCP) instead of product (XS)

Changed installer requirements

---

plugins/autocertkit

Bridge of disconnected NIC is not managable via XAPI. Hence xapi cannot provide its bridge name when dummy bridge exists for disconnected NIC.
Changed this ACK to try matching dummy bridge name in case it is native device but not identifiable via xapi call.

Improved device bridge name finder

---

autocertkit/ack_cli.py
autocertkit/test_generators.py

In order to make it possible for third-parties to run their own test cases inside of the ACK framework, this patch abstracts the generation stage of the XML by essentially registering a list of classes that:
* Take all of the state variables
* Generate a suitable number of test cases
This is made somewhat awkward because the existing generator classes assume a one device per set of test cases, hence for networking and storage we need to instantiate multiple generators, one for each device under test. 
Signed-off-by: Rob Dobson <rob.dobson@citrix.com>

Decoupling generation of test cases to make it easier to extend

---

autocertkit/ssh.py

ACK uses paramiko for SSH management.
When paramiko closes SSH connection, it explicitely calls close() method of socket, of which resource is collected when GC is called. This may prolong network connectivity in switch between 2 hops, which mat be different from route path that ACK tries to test.
By explcitly calling shutdown from socket object of SSHSession and force GC, we can override this 'alive' route path. As this route path is maintain in switch, ACK is doing its best efforts to reset route path.

Force close socket when use paramiko

---

autocertkit/network_tests.py
autocertkit/testbase.py

Iperf tests can fail occasionally due to intermittent iperf/network issue(s),
These are not ACK failure and rerun will avoid seeing noise.

Re-run iperf tests on failure once and log existing failure as warning.

---

autocertkit/ack_cli.py
autocertkit/test_generators.py

-e option now have CRASH to exclude CrashDump test form OperationTestClass

Make CrashDump test is optional (opt-in default)

---

autocertkit/utils.py

When function, which passed into TimeoutFunction class, raises unhandled
exception before timeout, ALARM may not cleared properly as it is outside
of try block. Moved alarm clear routine into finally block.

Fixed SIG issue

---

pylint.rc
pylint.sh

Existing code was obsolete and was not applicable. I have updated two files to run for latest ACK and will check all py files + ACK plugin, excluding XenAPI files.

updating pylint code to work with latest ACK

---

.travis.yml

Travis running for Xenserver/auto-cert-kit is often calling pip 8.1.2 and pip 7 and later do not support --use-mirrors option.
This is leading to travis check failure. Failure snippet is as below:
```
$ pip --version
pip 8.1.2 from /home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages (python 2.7)
$ pip install -r requirements.txt --use-mirrors
Usage:   
pip install [options] <requirement specifier> [package-index-options] ...
pip install [options] -r <requirements file> [package-index-options] ...
pip install [options] [-e] <vcs project url> ...
pip install [options] [-e] <local project path> ...
pip install [options] <archive url/path> ...
no such option: --use-mirrors
```

removing --use-mirrors as pip 7 and later no longer support it

---

mk/acktools-setup.py
setup.py

Ely no longer supports previous supp-pack packaging.

Updated to version 1.2.0

---

autocertkit/utils.py
plugins/autocertkit

ACK does pre-check if ack is also installed on slave or not. Since ACK is now an update hence need to check `rpm -qi`

CA-227289: ACK is now an update instead of supp-pack

---

autocertkit/networkconf.example

Signed-off-by: Yuan Ren <yuan.ren@citrix.com>

CA-292640: vlan_ids must be specified in NIC section.

---

autocertkit/network_tests.py
autocertkit/utils.py
plugins/autocertkit

In the case of signle subnet, the bonding etc test failed because reset_arp is called only when VM ethx0 enabled and other NIC is missing to config. The solution are
- Set all parameters *.arp_ignore=1
- Move reset_arp call after all VM NICs started
Signed-off-by: Deli Zhang <deli.zhang@citrix.com>

CA-374074: Fix reset_arp issue

---

acktools/__init__.py
acktools/log.py
acktools/net/route.py
acktools/net/tests/route_tests.py
acktools/tests/acktools_tests.py
acktools/utils.py
autocertkit/ack_cli.py
autocertkit/models.py
autocertkit/network_tests.py
autocertkit/ssh.py
autocertkit/status.py
autocertkit/test_generators.py
autocertkit/test_report.py
autocertkit/test_runner.py
autocertkit/testbase.py
autocertkit/tests/frontend-test.py
autocertkit/tests/model_tests.py
autocertkit/tests/test_generators_tests.py
autocertkit/tests/testbase_tests.py
autocertkit/tests/unittest_base.py
autocertkit/tests/utils_tests.py
autocertkit/tests/xenapi_mock.py
autocertkit/utils.py
plugins/autocertkit

All test passed
XenRT Job ID: 3717307, 3717308, 3717309, 3717310, 3717311

CP-41972: update ACK to python3 and fixed some problems

---

autocertkit/common.py

- If VM network has not yet started completely, ssh to it may encounter failure. Here the fix is raising the exception to let ssh command caller do retry.

CA-382842: Fix issue of "Connection refused"

---

plugins/autocertkit

If get_dev_pci_addr() does not match the __pci_addr_regex in the symlink in /sys/dev/block/* that matches the disk, it returns (-1, None). Nothing in plugins/autocertkit:840 checks for the error and _is_bus_id() blindly indexes its first argument directly: bus_id[-7:]. If bus_id was None, this would have raised an Exception.
Make _is_bus_id() more robust by checking that bus_id is not None before attempting to subscript it.

CP-46833: Fix 'NoneType' object is not subscriptable

---

autocertkit/utils.py

async is a keyword in python3.11
This commit rename async -> async_op

CP-48879: Rename async arg to async_op

---

autocertkit/utils.py

Use `is_alive` instead to work in XS9 (python3.11)
'is_alive' is also supported in python3.6 which is good for XS8.
https://docs.python.org/3.6/library/threading.html
Test passed: 4009814

CP-48851: `isAlive` has been removed since python3.8

---

autocertkit/ack_cli.py
autocertkit/testbase.py
autocertkit/utils.py
plugins/autocertkit

Since XS9, we use the eth name such as 'enp4s0f1' instead of 'ethx'
Tested:
xs8: 4366236
xs9: 4361397 (Use changlei’s private build and manually tested the ack changes)
```
[root@genus-34-55d auto-cert-kit]# ./status.py
0:Finished (Passed:41, Failed:1, Skipped:0)
The one failed case due to a  known issue.
```

CP-53745: Update for network renaming feature

---

autocertkit/utils.py

This service should be startup-ip.service.

CA-414165: Fix error: Failed to stop static-ip.service

---

autocertkit/ack_cli.py
autocertkit/utils.py

bridge is not supported since xs9
4416598 passed

CA-416185: Skip test cases using bridge as network backend for xs9
